/**
 * Refresh prisma/schema.prisma from a database, then fix what `prisma db pull` gets wrong
 * on this schema. Run against the LOCAL db built by `npm run db:local` — never production.
 *
 *   MIGRATE_DATABASE_URL=postgresql://postgres:localdev@localhost:54329/ros node scripts/prisma-pull.mjs
 *
 * Fix applied: public tables have foreign keys to BOTH auth.users and public.users, and db
 * pull names both relation fields `users`, which Prisma then rejects as a duplicate field.
 * Every relation field that points at auth_users is renamed `auth_user`.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const file = "prisma/schema.prisma";
// db pull refuses to start from an invalid schema, so always pull into the bare skeleton.
const SKELETON = `generator client {
  provider        = "prisma-client"
  output          = "../src/server/db/generated"
  previewFeatures = ["partialIndexes"]
}

datasource db {
  provider = "postgresql"
  // auth: only because public tables have foreign keys to auth.users (GoTrue owns it today).
  schemas  = ["auth", "public"]
}
`;
writeFileSync(file, SKELETON);
execSync("npx prisma db pull", { stdio: "inherit" });

const src = readFileSync(file, "utf8");
const fixed = src.replace(/^(\s+)users(\s+)(auth_users\??\s)/gm, (_m, a, b, c) => `${a}auth_user${b.slice(4) || " "}${c}`);
const header = [
  "// Generated by scripts/prisma-pull.mjs (`prisma db pull` + fixes) from the database built",
  "// out of supabase/baseline.sql + migrations. Policies, SECURITY DEFINER functions and",
  "// triggers are NOT modelled here — they live as SQL in prisma/migrations/*/migration.sql.",
  "// Import the client ONLY through @/server/db (lint + src/server/db/import-boundary.test.ts).",
  "",
].join("\n");
writeFileSync(file, header + fixed.replace(/^\/\/ Generated by scripts\/prisma-pull[\s\S]*?\n\n/, ""));
execSync("npx prisma validate", { stdio: "inherit" });
