/**
 * supabase/migrations/ is frozen at the Prisma Migrate baseline (prisma/migrations/0_init).
 * The deploy pipeline applies prisma/migrations only, so a new file in the old folder would
 * be committed, reviewed — and never reach the database. New migrations go in
 * prisma/migrations/<YYYYMMDDHHMMSS>_<name>/migration.sql.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "vitest";

/* 20261005110000 (R-163, payment runs) was written on manager-pardeep the same day the freeze
   landed on Abhishek; it is applied to staging and live the old way. The Prisma baseline
   (0_init) still needs it — see the merge note. */
const LAST_SUPABASE_MIGRATION = "20261005110000_payment_runs.sql";

/* Until R-161 reaches manager-pardeep, migrations written there still land in
   supabase/migrations and reach staging/live through the cloudsql deploy-db scripts (R-348,
   generated by scripts/ops/gen-deploy-db.mjs; 7 Oct 2026 staging train). A file a deploy-db
   script applies DOES reach the database, so it is allowed; anything else newer than the
   freeze is still refused. */
function appliedByDeployScripts(): Set<string> {
  const root = join(__dirname, "..", "..", "..", "supabase", "cloudsql");
  const names = new Set<string>();
  for (const env of ["staging", "live"]) {
    let files: string[] = [];
    try { files = readdirSync(join(root, env)).filter((f) => /^deploy-db-.*\.sh$/.test(f)); } catch { continue; }
    for (const f of files) {
      for (const m of readFileSync(join(root, env, f), "utf8").matchAll(/^\s*"[a-z0-9_]+\|([0-9]{14}_[a-z0-9_]+\.sql)\|/gm)) names.add(m[1]);
    }
  }
  return names;
}

test("no new files in supabase/migrations (use prisma/migrations)", () => {
  const dir = join(__dirname, "..", "..", "..", "supabase", "migrations");
  const applied = appliedByDeployScripts();
  /* R-531 (10 Oct 2026): a file whose top comment block says `-- deploy-skip:` is kept out of every deploy on purpose. */
  const skipped = (f: string) => {
    for (const line of readFileSync(join(dir, f), "utf8").split(/\r?\n/)) {
      if (!line.trim()) continue;
      if (!line.startsWith("--")) return false;
      if (/^--\s*deploy-skip:/.test(line)) return true;
    }
    return false;
  };
  const newer = readdirSync(dir).filter((f) => f.endsWith(".sql") && f > LAST_SUPABASE_MIGRATION && !applied.has(f) && !skipped(f));
  expect(newer).toEqual([]);
});

test("every Prisma migration folder holds a migration.sql and sorts after the baseline", () => {
  const dir = join(__dirname, "..", "..", "..", "prisma", "migrations");
  const folders = readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort();
  expect(folders[0]).toBe("0_init");
  for (const f of folders.slice(1)) {
    expect(f, "name must be <YYYYMMDDHHMMSS>_<name>").toMatch(/^\d{14}_[a-z0-9_]+$/);
    expect(readdirSync(join(dir, f))).toContain("migration.sql");
  }
});
