/**
 * R-262 — the tenant's compliance profile: business type + GST filing mode.
 *
 * Lives on tenants.business_type / tenants.gst_filing (migration
 * 20261007030000_tenant_compliance_profile.sql). The app has to keep working BEFORE that
 * migration is applied, so a "column does not exist" answer is not an error here: it reads
 * as an unknown profile, which gives the original Pvt Ltd / monthly-GST calendar, and the
 * settings card says the option is not switched on yet instead of failing a save.
 *
 * Read and written through an untyped client because the two columns are newer than
 * database.types.ts (shared, regenerated by the manager after the migration lands).
 */
"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { SupabaseClient } from "@supabase/supabase-js";
import { toast } from "sonner";

import { createClient } from "@/lib/supabase/client";
import { useCurrentUser } from "@/lib/hooks/useCurrentUser";
import type { BusinessType, GstFiling } from "./obligations";
import { profileFromRow, isMissingColumnError, type ComplianceProfileState } from "./profile-row";

/* R-325: the row helpers live in profile-row.ts (no client imports) so the cron can use them too. */
export { profileFromRow, isMissingColumnError, type ComplianceProfileState };

const untyped = () => createClient() as unknown as SupabaseClient;

export function useComplianceProfile() {
  const me = useCurrentUser();
  const tenantId = me.data?.tenantId ?? null;
  return useQuery({
    queryKey: ["compliance_profile", tenantId],
    enabled: Boolean(tenantId),
    queryFn: async (): Promise<ComplianceProfileState> => {
      const { data, error } = await untyped()
        .from("tenants")
        .select("business_type, gst_filing")
        .eq("id", tenantId as string)
        .maybeSingle();
      return profileFromRow(data as { business_type?: unknown; gst_filing?: unknown } | null, error);
    },
  });
}

export function useSaveComplianceProfile() {
  const qc = useQueryClient();
  const me = useCurrentUser();
  const tenantId = me.data?.tenantId ?? null;
  return useMutation({
    mutationFn: async (patch: { business_type?: BusinessType; gst_filing?: GstFiling }) => {
      if (!tenantId) throw new Error("Not signed in to a workspace");
      const { data, error } = await untyped().from("tenants").update(patch).eq("id", tenantId).select("id");
      if (isMissingColumnError(error)) {
        throw new Error("This option is not switched on yet — it needs a database update first.");
      }
      if (error) throw new Error(error.message);
      // RLS lets only the owner update the tenant row; anyone else gets zero rows, not an error.
      if (!data || data.length === 0) throw new Error("Only the workspace owner can change this.");
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["compliance_profile"] });
      toast.success("Compliance profile saved");
    },
    onError: (err) => toast.error(`Could not save: ${(err as Error).message}`),
  });
}
